# Generated by Django 3.1.2 on 2020-11-24 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('apellido', models.CharField(max_length=32)),
                ('especialidad', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('apellido', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cumplio', models.BooleanField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_medico', to='optometria.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_paciente', to='optometria.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_pago', models.CharField(choices=[('credito', 'Tarjeta de Crédito'), ('debito', 'Tarjeta de Débito'), ('virtual', 'Billetera Virtual'), ('efectivo', 'Efectivo')], default='efectivo', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pedido', 'Pedido'), ('taller', 'Taller'), ('finalizado', 'Finalizado')], default='pendiente', max_length=12)),
                ('items', models.ManyToManyField(to='optometria.Producto')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pedido_paciente', to='optometria.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Hc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('detalle', models.TextField()),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hc_paciente', to='optometria.paciente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hc_medico', to='optometria.medico')),
            ],
        ),
    ]
