# Generated by Django 3.1.2 on 2020-12-02 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cumplio', models.BooleanField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_pago', models.CharField(choices=[('credito', 'Tarjeta de Crédito'), ('debito', 'Tarjeta de Débito'), ('virtual', 'Billetera Virtual'), ('efectivo', 'Efectivo')], default='efectivo', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pedido', 'Pedido'), ('taller', 'Taller'), ('finalizado', 'Finalizado')], default='pendiente', max_length=12)),
                ('fecha', models.DateField()),
                ('items', models.ManyToManyField(to='optometria.Producto')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pedido_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.CharField(choices=[('cerca', 'Cerca'), ('lejos', 'Lejos')], default='cerca', max_length=16)),
                ('lado', models.CharField(choices=[('izquierdo', 'Izquierdo'), ('derecho', 'Derecho')], default='izquierdo', max_length=16)),
                ('armazon', models.BooleanField(default=False)),
                ('precio', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lente_pedido', to='optometria.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Hc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True)),
                ('detalle', models.TextField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hc_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hc_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
