# Generated by Django 3.1.2 on 2020-12-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lente',
            name='pedido',
        ),
    ]
