# Generated by Django 3.1.2 on 2020-11-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hc',
            old_name='Paciente',
            new_name='paciente',
        ),
    ]
