# Generated by Django 3.1.2 on 2020-11-30 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0002_pedido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='lente',
            name='pedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_lente', to='optometria.pedido'),
            preserve_default=False,
        ),
    ]
