# Generated by Django 3.1.2 on 2020-11-24 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('optometria', '0002_auto_20201123_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hc',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hc_medico', to=settings.AUTH_USER_MODEL),
        ),
    ]
