# Generated by Django 3.1.2 on 2020-12-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0002_remove_lente_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='lente',
            name='pedido',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, related_name='lente_pedido', to='optometria.pedido'),
            preserve_default=False,
        ),
    ]
