# Generated by Django 3.1.2 on 2020-11-30 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0003_lente_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lente',
            name='pedido',
        ),
        migrations.AddField(
            model_name='lente',
            name='producto_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='optometria.producto'),
            preserve_default=False,
        ),
    ]
