# Generated by Django 3.1.2 on 2020-11-24 04:13

from django.db import migrations, models
import optometria.models


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0003_auto_20201123_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio',
            field=models.FloatField(default=0, verbose_name=optometria.models.Pedido.precio),
            preserve_default=False,
        ),
    ]
