# Generated by Django 3.1.2 on 2020-12-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0004_remove_lente_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lente',
        ),
    ]
