# Generated by Django 3.1.2 on 2020-12-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0004_auto_20201130_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lente',
            name='producto_ptr',
        ),
        migrations.AddField(
            model_name='lente',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lente',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
