# Generated by Django 3.1.2 on 2020-11-27 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import optometria.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('optometria', '0018_auto_20201126_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hc',
            name='fecha',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='hc',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hc_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hc',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hc_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.FloatField(verbose_name=optometria.models.Pedido.precio),
        ),
    ]
