# Generated by Django 3.1.2 on 2020-11-27 02:29

from django.db import migrations, models
import optometria.models


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0019_auto_20201126_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.CharField(choices=[('cerca', 'Cerca'), ('lejos', 'Lejos')], default='cerca', max_length=16)),
                ('lado', models.CharField(choices=[('izquierdo', 'Izquierdo'), ('derecho', 'Derecho')], default='izquierdo', max_length=16)),
                ('armazon', models.BooleanField(default=False, verbose_name='con armazon/sin armazon')),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.FloatField(verbose_name=optometria.models.Pedido.precio),
        ),
    ]
