# Generated by Django 3.1.2 on 2020-11-27 11:10

from django.db import migrations, models
import django.db.models.deletion
import optometria.models


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0020_auto_20201126_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lente',
            name='id',
        ),
        migrations.AddField(
            model_name='lente',
            name='producto_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='optometria.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.FloatField(verbose_name=optometria.models.Pedido.precio),
        ),
    ]
