# Generated by Django 3.1.2 on 2020-11-27 14:10

from django.db import migrations, models
import optometria.models


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0021_auto_20201127_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lente',
            name='producto_ptr',
        ),
        migrations.AddField(
            model_name='lente',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.FloatField(verbose_name=optometria.models.Pedido.precio),
        ),
    ]
