# Generated by Django 3.1.2 on 2020-11-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0023_auto_20201127_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='precio',
        ),
    ]
